defaults:
  - _self_
  - task: pointmaze-large-navigate-v0
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

group: debug

pipeline_name: stitcher_ogbench
mode: train
seed: 0
device: cuda:0

# Diffuser
solver: ddim
ema_rate: 0.9999
sampling_steps: 20

# Training
diffusion_gradient_steps: 1000000
batch_size: 64
log_interval: 1000
save_interval: 100000
use_mask_strategy: True

# Generate Data
dataset_size_limit: 1000000
num_episodes_to_generate: 5000
use_hilp_for_rollout: True
latent_dim: 32
k_neighbors_rollout: 10
k_density: 30
alpha: 1.0
beta: 2.0
temperature: 0.5
use_ema: True


# hydra
hydra:
  run:
    dir: .         
  output_subdir: null   
