defaults:
  - _self_
  - task: pointmaze-large-stitch-v0
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

group: debug

pipeline_name: scots_ogbench
mode: train
seed: 0
device: cuda:0

# Diffuser
solver: ddim
ema_rate: 0.9999
sampling_steps: 20

# Training
diffusion_gradient_steps: 1000000
batch_size: 64
log_interval: 1000
save_interval: 100000
use_mask_strategy: True

# Inference
diffusion_ckpt: latest
num_candidates: 1
temperature: 0.5
use_ema: True
video_episodes: 1
eval_episodes: 50
frame_skip: 3
low_eval_temperature: 0.01


# hydra
hydra:
  run:
    dir: .         
  output_subdir: null   
